/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_mcmodule_silk_Native */

#ifndef _Included_org_mcmodule_silk_Native
#define _Included_org_mcmodule_silk_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_mcmodule_silk_Native
 * Method:    getVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_mcmodule_silk_Native_getVersion
  (JNIEnv *, jclass);

/*
 * Class:     org_mcmodule_silk_Native
 * Method:    getEncoderSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_mcmodule_silk_Native_getEncoderSize
  (JNIEnv *, jclass);

/*
 * Class:     org_mcmodule_silk_Native
 * Method:    initEncoder
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_mcmodule_silk_Native_initEncoder
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_mcmodule_silk_Native
 * Method:    queryEncoder
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_mcmodule_silk_Native_queryEncoder
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_mcmodule_silk_Native
 * Method:    encode
 * Signature: (JJ[SII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_mcmodule_silk_Native_encode
  (JNIEnv *, jclass, jlong, jlong, jshortArray, jint, jint);

/*
 * Class:     org_mcmodule_silk_Native
 * Method:    getDecoderSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_mcmodule_silk_Native_getDecoderSize
  (JNIEnv *, jclass);

/*
 * Class:     org_mcmodule_silk_Native
 * Method:    initDecoder
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_mcmodule_silk_Native_initDecoder
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_mcmodule_silk_Native
 * Method:    decode
 * Signature: (JJZ[BII)[S
 */
JNIEXPORT jshortArray JNICALL Java_org_mcmodule_silk_Native_decode
  (JNIEnv *, jclass, jlong, jlong, jboolean, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
